### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by fabianofrank** [fabianofrank/pokemon-api#19]
Choose images, text, icons, fonts.

**Comment by danalvrz** [comment]
- [ ] Chose images and overall style: https://github.com/skydoves/Pokedex
- [ ] Chose font style: https://www.dafont.com/pokemon-classic.font
- [ ] Chose images: https://pokeapi.co
- [ ] Chose icons: https://www.flaticon.com/premium-icon/pokeball_280954?term=pokemon&page=1&position=3&page=1&position=3&related_id=280954&origin=search
